cursor #dee4e1
cursor_text_color #bec9c5

foreground            #dee4e1
background            #0e1513
selection_foreground  #1c352f
selection_background  #b1ccc4
url_color             #84d5c4

color0   #0e1513
color1   #f49b6e
color2   #6ad570
color3   #fff372
color4   #6ecab6
color5   #1d6254
color6   #84d5c4
color7   #d2dfdc
color8   #3c4442
color9   #ffbf9f
color10  #a5ffab
color11  #fff7a5
color12  #9eeada
color13  #bbfff0
color14  #d3fff5
color15  #f8fffd
