font_family GeistMono Nerd Font
font_size 12

disable_ligatures yes
enable_audio_bell no


cursor_shape block
url_style curly

# Keep Kitty from drawing its own title bar and buttons.
hide_window_decorations yes

remember_window_size no
initial_window_width 78c
initial_window_height 23c
window_padding_width 30
cursor_blink_interval 0

background_opacity 0.70
confirm_os_window_close 0

# Performance settings
sync_to_monitor no
