# bind (bind=MOD[+MOD],BIND,ACTION,ARG)

--Main binds
bind=SUPER,w,spawn,ghostty #"Terminal"
bind=SUPER,q,killclient
bind=SUPER,e,spawn,ghostty --title=Yazi -e yazi
bind=SUPER,r,spawn_shell,mmsg reload_config && noctalia msg notification-show "Mango recarregado" "Configuração atualizada"

--Mango
bind=SUPER+Alt,F4,quit

--Noctalia
bind=SUPER,d,spawn,noctalia msg panel-toggle launcher
bind=SUPER,F2,spawn,noctalia msg panel-toggle clipboard
bind=SUPER,Escape,spawn,noctalia msg panel-toggle session
bind=SUPER,F1,spawn,noctalia msg panel-toggle kenn/keybind-cheatsheet:cheatsheet
bind=NONE,Print,spawn,noctalia msg screenshot-region
bind=NONE,XF86AudioRaiseVolume,spawn,noctalia msg volume-up
bind=NONE,XF86AudioLowerVolume,spawn,noctalia msg volume-down
bind=NONE,XF86AudioMute,spawn,noctalia msg volume-mute
bind=NONE,XF86MonBrightnessUp,spawn,noctalia msg brightness-up
bind=NONE,XF86MonBrightnessDown,spawn,noctalia msg brightness-down

--Window
bind=SUPER+SHIFT,f,togglefullscreen
#bind=SUPER,f,togglemaximizescreen
bind=SUPER,f,set_proportion,1.0
bind=SUPER,v,togglefloating

mousebind=SUPER,btn_left,moveresize,curmove
mousebind=SUPER,btn_right,moveresize,curresize

bind=SUPER,equal,resizewin,+150,0
bind=SUPER,minus,resizewin,-150,0
bind=SUPER,Prior,set_proportion,0.5
bind=SUPER,Next,set_proportion,0.8

--Navigation
bind=SUPER,h,focusdir,left
bind=SUPER,k,focusdir,up
bind=SUPER,j,focusdir,down
bind=SUPER,l,focusdir,right
bind=SUPER,left,focusdir,left
bind=SUPER,up,focusdir,up
bind=SUPER,down,focusdir,down
bind=SUPER,right,focusdir,right

bind=SUPER,1,view,1,0
bind=SUPER,2,view,2,0
bind=SUPER,3,view,3,0
bind=SUPER,4,view,4,0
bind=SUPER,5,view,5,0
bind=SUPER,6,view,6,0
bind=SUPER,7,view,7,0
bind=SUPER,8,view,8,0
bind=SUPER,9,view,9,0

bind=SUPER+SHIFT,1,tag,1
bind=SUPER+SHIFT,2,tag,2
bind=SUPER+SHIFT,3,tag,3
bind=SUPER+SHIFT,4,tag,4
bind=SUPER+SHIFT,5,tag,5
bind=SUPER+SHIFT,6,tag,6
bind=SUPER+SHIFT,7,tag,7
bind=SUPER+SHIFT,8,tag,8
bind=SUPER+SHIFT,9,tag,9

bind=SUPER+CTRL,1,tagsilent,1
bind=SUPER+CTRL,2,tagsilent,2
bind=SUPER+CTRL,3,tagsilent,3
bind=SUPER+CTRL,4,tagsilent,4
bind=SUPER+CTRL,5,tagsilent,5
bind=SUPER+CTRL,6,tagsilent,6
bind=SUPER+CTRL,7,tagsilent,7
bind=SUPER+CTRL,8,tagsilent,8
bind=SUPER+CTRL,9,tagsilent,9

bind=SUPER+SHIFT,h,exchange_client,left
bind=SUPER+SHIFT,l,exchange_client,right
bind=SUPER+SHIFT,left,exchange_client,left
bind=SUPER+SHIFT,right,exchange_client,right
bind=SUPER+SHIFT,k,exchange_client,up
bind=SUPER+SHIFT,j,exchange_client,down
bind=SUPER+SHIFT,up,exchange_client,up
bind=SUPER+SHIFT,down,exchange_client,down

bind=SUPER,home,focusmon,right
bind=SUPER+SHIFT,home,tagmon,right
bind=SUPER+CTRL,home,spawn,~/.config/mango/scripts/move-window-right-silent.sh

--DEBUG
#bind=SUPER+SHIFT,i,spawn,ghostty -e sh -c 'mmsg get focusing-client; read'

--SCRIPT
bind=SUPER,F8,spawn_shell,macro-toggle portal
