source=./binds.conf
source=./devices.conf
source=./rules.conf
source=./decorations.conf

exec-once=noctalia
sloppyfocus=0

# ponte do text-input-v3 (veja o comentário em modules/common.nix)
# — mango não processa autostart XDG sozinho, precisa disso aqui.
exec-once=fcitx5

source=./noctalia.conf
