--keyboard
xkb_rules_layout=us,br
xkb_rules_options=caps:escape
repeat_rate=30
repeat_delay=400

--mouse
mouse_accel_profile=2
mouse_accel_speed=-0.6



--trackpad
mouse_scroll_method = 2
natural_scrolling=0
