# tile,scroller,grid,deck,monocle,center_tile,vertical_tile,vertical_scroller
tagrule=id:*,layout_name:scroller

#windowrule=isfloating:1,title:^Yazi$

devicerule=name:ydotoold virtual device,accel_profile:0,accel_speed:0
